//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoKeDBEntities : DbContext
    {
        public BoKeDBEntities()
            : base("name=BoKeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<CommentsB> CommentsB { get; set; }
        public virtual DbSet<CommentsD> CommentsD { get; set; }
        public virtual DbSet<Community> Community { get; set; }
        public virtual DbSet<Concern> Concern { get; set; }
        public virtual DbSet<courseel> courseel { get; set; }
        public virtual DbSet<Download> Download { get; set; }
        public virtual DbSet<Favorite> Favorite { get; set; }
        public virtual DbSet<Followers> Followers { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Issue> Issue { get; set; }
        public virtual DbSet<Label> Label { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<Reply> Reply { get; set; }
        public virtual DbSet<Search> Search { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<BlogLike> BlogLike { get; set; }
        public virtual DbSet<Communitymember> Communitymember { get; set; }
        public virtual DbSet<course> course { get; set; }
    }
}
