//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseel
    {
        public int courseelId { get; set; }
        public Nullable<int> courseelpf { get; set; }
        public string courseelcontent { get; set; }
        public Nullable<int> courseId { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
