//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int courseId { get; set; }
        public string courseName { get; set; }
        public string coursePicUrl { get; set; }
        public Nullable<decimal> originalPrice { get; set; }
        public Nullable<int> courseHit { get; set; }
        public string courseDec { get; set; }
    }
}
