//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int DownloadID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> frequency { get; set; }
        public string DownloadPath { get; set; }
        public string DownloadName { get; set; }
        public string DownloadDec { get; set; }
        public Nullable<int> DownloadKunCoin { get; set; }
        public Nullable<int> DownloadKunCoinObtain { get; set; }
        public Nullable<int> LabelID { get; set; }
        public string DownloadTime { get; set; }
        public string suffix { get; set; }
    }
}
