//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UserBirthday { get; set; }
        public string UserPhone { get; set; }
        public string UserAddress { get; set; }
        public string UserProfile { get; set; }
        public string UserLabel { get; set; }
        public string UserAvatarUrl { get; set; }
        public Nullable<int> UserVIP { get; set; }
        public Nullable<int> UserKunCoin { get; set; }
        public Nullable<int> UserExperience { get; set; }
        public Nullable<System.DateTime> UserlastLoginTime { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public Nullable<int> FavoriteCount { get; set; }
        public Nullable<int> DownloadKunCoinObtainCount { get; set; }
    }
}
